

const SLUGS = {
    admin:{
        slug:"/admin",
        children:[]
    },
    login:{
        slug:"/login",
        children:[]
    },
    signup:{
        slug:"/signup",
        children:[]
    },
    forgot_pasword:{
        slug:"/forgot-password",
        children:[]
    },
    calendar:{
        slug:"/calendar",
        children:[]
    },
    confidential:{
        slug:"/confidential",
        children:[]
    },
    dashboard:{
        slug:"/dashboard",
        children:[]
    },
    game:{
        slug:"/game",
        children:[]
    },
    graphs:{
        slug:"/graphs",
        children:[]
    },
    home:{
        slug:"/home",
        children:[]
    },
    live:{
        slug:"/live",
        children:[]
    },
    masterlist:{
        slug:"/masterlist",
        children:[]
    },
    meals:{
        slug:"/meals",
        children:[]
    },
    objectives:{
        slug:"/objectives",
        children:[]
    },
    planner:{
        slug:"/planner",
        children:[]
    },
    reccuring:{
        slug:"/reccuring",
        children:[]
    },
    routines:{
        slug:"/routines",
        children:[]
    },
    saveditems:{
        slug:"/saveditems",
        children:[]
    },
    settings:{
        slug:"/settings",
        children:[]
    },
    stats:{
        slug:"/stats",
        children:[]
    },
    templates:{
        slug:"/templates",
        children:[]
    },
    today:{
        slug:"/today",
        children:[]
    },
    wiki:{
        slug:"/wiki",
        children:[]
    },
    workspace:{
        slug:"/workspace",
        children:[]
    },
    access_denied:{
        slug:"/access-denied",
        children:[]
    },


}

export default SLUGS

